FROM ubuntu:18.04
MAINTAINER sk1.project.org@gmail.com
 
RUN apt-get update && apt-get install -y libcairo2-dev liblcms2-dev libmagickwand-dev libpango1.0-dev python-dev python-cairo-dev
 
CMD ["/sk1-wx/bbox.py"]