# -*- coding: utf-8 -*-
#
#  Copyright (C) 2015 by Ihor E. Novikov
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

DEFAULT_PATTERN = 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAA' \
                  'AAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAAB' \
                  'cBAwABAAAAIAAAABwBAwABAAAAAQAAAAAAAAAA/wD/AP8A/wD/AP8A/' \
                  'wD//wD/AP8A/wD/AP8A/wD/AA=='

PATTERN1 = 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAAB' \
           'wBAwABAAAAAQAAAAAAAAAA/wD/AP8A/wD/AP8A/wD//wD/AP8A/wD/AP8A/wD/AA=='

PATTERN2 = 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAAB' \
           'wBAwABAAAAAQAAAAAAAADv7+8A7+/v7w=='

PATTERN3 = 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAAB' \
           'wBAwABAAAAAQAAAAAAAADn5+cAAOfn5w=='

PATTERN4 = 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAAB' \
           'wBAwABAAAAAQAAAAAAAAD///8A/////w=='

PATTERN5 = 'SUkqAAgAAAAIAAABAwABAAAABAAAAAEBAwABAAAABAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAABAAAABcBAwABAAAABAAAAB' \
           'wBAwABAAAAAQAAAAAAAADwAPDw'

PATTERN6 = 'SUkqAAgAAAAIAAABAwABAAAABAAAAAEBAwABAAAABAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAABAAAABcBAwABAAAABAAAAB' \
           'wBAwABAAAAAQAAAAAAAADwAADw'

PATTERN7 = 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAAB' \
           'wBAwABAAAAAQAAAAAAAAD+/fv379+/fw=='

PATTERN8 = 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAAB' \
           'wBAwABAAAAAQAAAAAAAADv/+//7/8B/+//7//v/////+//7//v/wH/7//v/+///w=='

PATTERN9 = 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAY' \
           'BAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAAB' \
           'wBAwABAAAAAQAAAAAAAAA/P97t8/Pt3g=='

PATTERN10 = 'SUkqAAgAAAAIAAABAwABAAAADwAAAAEBAwABAAAACwAAAAMBAwABAAAAAQAAAA' \
            'YBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACwAAABcBAwABAAAAFgAA' \
            'ABwBAwABAAAAAQAAAAAAAAAAAP/8//r/9v/u/97/vv9+/v79/vv+'

PATTERN11 = 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAA' \
            'YBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAA' \
            'ABwBAwABAAAAAQAAAAAAAAD///////////f++/39+/73/2//n/+f/2/+9/37+/' \
            '33/g=='

PATTERN12 = 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAA' \
            'YBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAA' \
            'ABwBAwABAAAAAQAAAAAAAAAAAH//f/9//3//f/9//3//AAD/f/9//3//f/9//3' \
            '//fw=='

PATTERN_PRESETS = [PATTERN1, PATTERN2, PATTERN3, PATTERN4, PATTERN5, PATTERN6,
                   PATTERN7, PATTERN8, PATTERN9, PATTERN10, PATTERN11,
                   PATTERN12]
