# -*- coding: utf-8 -*-
#
#	Copyright (C) 2015 by Igor E. Novikov
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.

DEFAULT_PATTERN = 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAABwBAwABAAAAAQAAAAAAAAAA/wD/AP8A/wD/AP8A/wD//wD/AP8A/wD/AP8A/wD/AA=='

PATTERN_PRESETS = ['SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAABwBAwABAAAAAQAAAAAAAAAA/wD/AP8A/wD/AP8A/wD//wD/AP8A/wD/AP8A/wD/AA==', 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAABwBAwABAAAAAQAAAAAAAADv7+8A7+/v7w==', 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAABwBAwABAAAAAQAAAAAAAADn5+cAAOfn5w==', 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAABwBAwABAAAAAQAAAAAAAAD///8A/////w==', 'SUkqAAgAAAAIAAABAwABAAAABAAAAAEBAwABAAAABAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAABAAAABcBAwABAAAABAAAABwBAwABAAAAAQAAAAAAAADwAPDw', 'SUkqAAgAAAAIAAABAwABAAAABAAAAAEBAwABAAAABAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAABAAAABcBAwABAAAABAAAABwBAwABAAAAAQAAAAAAAADwAADw', 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAABwBAwABAAAAAQAAAAAAAAD+/fv379+/fw==', 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAABwBAwABAAAAAQAAAAAAAADv/+//7/8B/+//7//v/////+//7//v/wH/7//v/+///w==', 'SUkqAAgAAAAIAAABAwABAAAACAAAAAEBAwABAAAACAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACAAAABcBAwABAAAACAAAABwBAwABAAAAAQAAAAAAAAA/P97t8/Pt3g==', 'SUkqAAgAAAAIAAABAwABAAAADwAAAAEBAwABAAAACwAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAACwAAABcBAwABAAAAFgAAABwBAwABAAAAAQAAAAAAAAAAAP/8//r/9v/u/97/vv9+/v79/vv+', 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAABwBAwABAAAAAQAAAAAAAAD///////////f++/39+/73/2//n/+f/2/+9/37+/33/g==', 'SUkqAAgAAAAIAAABAwABAAAAEAAAAAEBAwABAAAAEAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAAEAAAABcBAwABAAAAIAAAABwBAwABAAAAAQAAAAAAAAAAAH//f/9//3//f/9//3//AAD/f/9//3//f/9//3//fw==']