# -*- coding: utf-8 -*-
#
# 	Copyright (C) 2016 by Igor E. Novikov
#
# 	This program is free software: you can redistribute it and/or modify
# 	it under the terms of the GNU General Public License as published by
# 	the Free Software Foundation, either version 3 of the License, or
# 	(at your option) any later version.
#
# 	This program is distributed in the hope that it will be useful,
# 	but WITHOUT ANY WARRANTY; without even the implied warranty of
# 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 	GNU General Public License for more details.
#
# 	You should have received a copy of the GNU General Public License
# 	along with this program.  If not, see <http://www.gnu.org/licenses/>.

from uc2.formats.wmf import wmfconst

WMF_HATCHES = {
wmfconst.HS_HORIZONTAL :'SUkqAAgAAAAIAAABAwABAAAABAAAAAEBAwABAAAABAAAAAMBAwABAAAAAQAAAAYBAwABAAAAAQAAABEBBAABAAAAbgAAABYBAwABAAAABAAAABcBAwABAAAABAAAABwBAwABAAAAAQAAAAAAAADwAPDw',
wmfconst.HS_VERTICAL :'SUkqAEgAAAD/////AAAA/////////////////wAAAP////////////////8AAAD/////////////////AAAA////////////DAAAAQMAAQAAAAQAAAABAQMAAQAAAAQAAAACAQMABAAAAO4AAAADAQMAAQAAAAEAAAAGAQMAAQAAAAIAAAARAQQAAQAAAAgAAAAVAQMAAQAAAAQAAAAXAQQAAQAAAEAAAAAaAQUAAQAAAN4AAAAbAQUAAQAAAOYAAAAcAQMAAQAAAAEAAAAoAQMAAQAAAAIAAAAAAAAAYAAAAAEAAABgAAAAAQAAAAgACAAIAAgA',
wmfconst.HS_BDIAGONAL :'SUkqAEgAAAD///////////////8AAAD///////////8AAAD///////////8AAAD///////////8AAAD/////////////////DAAAAQMAAQAAAAQAAAABAQMAAQAAAAQAAAACAQMABAAAAO4AAAADAQMAAQAAAAEAAAAGAQMAAQAAAAIAAAARAQQAAQAAAAgAAAAVAQMAAQAAAAQAAAAXAQQAAQAAAEAAAAAaAQUAAQAAAN4AAAAbAQUAAQAAAOYAAAAcAQMAAQAAAAEAAAAoAQMAAQAAAAIAAAAAAAAAYAAAAAEAAABgAAAAAQAAAAgACAAIAAgA',
wmfconst.HS_FDIAGONAL :'SUkqAEgAAAAAAAD//////////////////////wAAAP//////////////////////AAAA//////////////////////8AAAD/DAAAAQMAAQAAAAQAAAABAQMAAQAAAAQAAAACAQMABAAAAO4AAAADAQMAAQAAAAEAAAAGAQMAAQAAAAIAAAARAQQAAQAAAAgAAAAVAQMAAQAAAAQAAAAXAQQAAQAAAEAAAAAaAQUAAQAAAN4AAAAbAQUAAQAAAOYAAAAcAQMAAQAAAAEAAAAoAQMAAQAAAAIAAAAAAAAAYAAAAAEAAABgAAAAAQAAAAgACAAIAAgA',
wmfconst.HS_CROSS :'SUkqAEgAAAD/////AAAA/////////////////wAAAP////////////////8AAAD///////////8AAAD/AAAA/wAAAP8AAAD/DAAAAQMAAQAAAAQAAAABAQMAAQAAAAQAAAACAQMABAAAAO4AAAADAQMAAQAAAAEAAAAGAQMAAQAAAAIAAAARAQQAAQAAAAgAAAAVAQMAAQAAAAQAAAAXAQQAAQAAAEAAAAAaAQUAAQAAAN4AAAAbAQUAAQAAAOYAAAAcAQMAAQAAAAEAAAAoAQMAAQAAAAIAAAAAAAAAYAAAAAEAAABgAAAAAQAAAAgACAAIAAgA',
wmfconst.HS_DIAGCROSS :'SUkqAEgAAAAAAAD//////////////////////wAAAP//////AAAA////////////AAAA////////////AAAA//////8AAAD/DAAAAQMAAQAAAAQAAAABAQMAAQAAAAQAAAACAQMABAAAAO4AAAADAQMAAQAAAAEAAAAGAQMAAQAAAAIAAAARAQQAAQAAAAgAAAAVAQMAAQAAAAQAAAAXAQQAAQAAAEAAAAAaAQUAAQAAAN4AAAAbAQUAAQAAAOYAAAAcAQMAAQAAAAEAAAAoAQMAAQAAAAIAAAAAAAAAYAAAAAEAAABgAAAAAQAAAAgACAAIAAgA',
}
