# 
#
#  Copyright (C) = 2019 by Maxim S. Barabash
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version = 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https:#www.gnu.org/licenses/>.


XAR_SIGNATURE = 0x41524158  # characters "XARA"
XAR_DFC = 0xa0da3a3  # detect file corruption


STRING_TERMINATOR = b"\0\0"
ASCII_STRING_TERMINATOR = b"\0"



#Navigation records
TAG_UP = 0
TAG_DOWN = 1
TAG_FILEHEADER = 2
TAG_ENDOFFILE = 3

# Tag management
TAG_ATOMICTAGS = 10
TAG_ESSENTIALTAGS = 11
TAG_TAGDESCRIPTION = 12

# Compression tags
TAG_STARTCOMPRESSION = 30
TAG_ENDCOMPRESSION = 31

# Document tags
TAG_DOCUMENT = 40
TAG_CHAPTER = 41
TAG_SPREAD = 42

# Notes

TAG_LAYER = 43
TAG_PAGE = 44
TAG_SPREADINFORMATION = 45
TAG_GRIDRULERSETTINGS = 46
TAG_GRIDRULERORIGIN = 47
TAG_LAYERDETAILS = 48
TAG_GUIDELAYERDETAILS = 49
TAG_SPREADSCALING_ACTIVE = 52
TAG_SPREADSCALING_INACTIVE = 53

# Colour reference tags
TAG_DEFINERGBCOLOUR = 50
TAG_DEFINECOMPLEXCOLOUR = 51

# Bitmap reference tags
RESERVED_60 = 60
TAG_PREVIEWBITMAP_GIF = 61
TAG_PREVIEWBITMAP_JPEG = 62
TAG_PREVIEWBITMAP_PNG = 63
RESERVED_64 = 64
RESERVED_65 = 65
RESERVED_66 = 66
TAG_DEFINEBITMAP_JPEG = 67
TAG_DEFINEBITMAP_PNG = 68
RESERVED_69 = 69
RESERVED_70 = 70
TAG_DEFINEBITMAP_JPEG8BPP = 71

# View tags
TAG_VIEWPORT = 80
TAG_VIEWQUALITY = 81
TAG_DOCUMENTVIEW = 82

# Document unit tags
TAG_DEFINE_PREFIXUSERUNIT = 85
TAG_DEFINE_SUFFIXUSERUNIT = 86
TAG_DEFINE_DEFAULTUNITS = 87

# Document info tags
TAG_DOCUMENTCOMMENT = 90
TAG_DOCUMENTDATES = 91
TAG_DOCUMENTUNDOSIZE = 92
TAG_DOCUMENTFLAGS = 93
TAG_DOCUMENTINFORMATION = 4136

# Object tags
TAG_PATH = 100
TAG_PATH_FILLED = 101
TAG_PATH_STROKED = 102
TAG_PATH_FILLED_STROKED = 103
TAG_GROUP = 104
TAG_BLEND = 105
TAG_BLENDER = 106
TAG_MOULD_ENVELOPE = 107
TAG_MOULD_PERSPECTIVE = 108
TAG_MOULD_GROUP = 109
TAG_MOULD_PATH = 110
TAG_PATH_FLAGS = 111
TAG_GUIDELINE = 112
TAG_PATH_RELATIVE = 113
TAG_PATH_RELATIVE_FILLED = 114
TAG_PATH_RELATIVE_STROKED = 115
TAG_PATH_RELATIVE_FILLED_STROKED = 116
RESERVED_117 = 117
TAG_PATHREF_TRANSFORM = 118

# Attribute tags
TAG_FLATFILL = 150
TAG_LINECOLOUR = 151
TAG_LINEWIDTH = 152
TAG_LINEARFILL = 153
TAG_CIRCULARFILL = 154
TAG_ELLIPTICALFILL = 155
TAG_CONICALFILL = 156
TAG_BITMAPFILL = 157
TAG_CONTONEBITMAPFILL = 158
TAG_FRACTALFILL = 159
TAG_FILLEFFECT_FADE = 160
TAG_FILLEFFECT_RAINBOW = 161
TAG_FILLEFFECT_ALTRAINBOW = 162
TAG_FILL_REPEATING = 163
TAG_FILL_NONREPEATING = 164
TAG_FILL_REPEATINGINVERTED = 165
TAG_FLATTRANSPARENTFILL = 166
TAG_LINEARTRANSPARENTFILL = 167
TAG_CIRCULARTRANSPARENTFILL = 168
TAG_ELLIPTICALTRANSPARENTFILL = 169
TAG_CONICALTRANSPARENTFILL = 170
TAG_BITMAPTRANSPARENTFILL = 171
TAG_FRACTALTRANSPARENTFILL = 172
TAG_LINETRANSPARENCY = 173
TAG_STARTCAP = 174
TAG_ENDCAP = 175
TAG_JOINSTYLE = 176
TAG_MITRELIMIT = 177
TAG_WINDINGRULE = 178
TAG_QUALITY = 179
TAG_TRANSPARENTFILL_REPEATING = 180
TAG_TRANSPARENTFILL_NONREPEATING = 181
TAG_TRANSPARENTFILL_REPEATINGINVERTED = 182

# Arrows and dash patterns
TAG_DASHSTYLE = 183
TAG_DEFINEDASH = 184
TAG_ARROWHEAD = 185
TAG_ARROWTAIL = 186
TAG_DEFINEARROW = 187
TAG_DEFINEDASH_SCALED = 188

# User Attributes
TAG_USERVALUE = 189

# special colour fills
TAG_FLATFILL_NONE = 190
TAG_FLATFILL_BLACK = 191
TAG_FLATFILL_WHITE = 192
TAG_LINECOLOUR_NONE = 193
TAG_LINECOLOUR_BLACK = 194
TAG_LINECOLOUR_WHITE = 195

# Bitmaps
TAG_NODE_BITMAP = 198
TAG_NODE_CONTONEDBITMAP = 199

# New fill type records
TAG_DIAMONDFILL = 200
TAG_DIAMONDTRANSPARENTFILL = 201
TAG_THREECOLFILL = 202
TAG_THREECOLTRANSPARENTFILL = 203
TAG_FOURCOLFILL = 204
TAG_FOURCOLTRANSPARENTFILL = 205
TAG_FILL_REPEATING_EXTRA = 206
TAG_TRANSPARENTFILL_REPEATING_EXTRA = 207

# Regular shapes
# Ellipses
TAG_ELLIPSE_SIMPLE = 1000
TAG_ELLIPSE_COMPLEX = 1001

# Rectangles
TAG_RECTANGLE_SIMPLE = 1100
TAG_RECTANGLE_SIMPLE_REFORMED = 1101  # Deprecated
TAG_RECTANGLE_SIMPLE_STELLATED = 1102  # Deprecated
TAG_RECTANGLE_SIMPLE_STELLATED_REFORMED = 1103  # Deprecated
TAG_RECTANGLE_SIMPLE_ROUNDED = 1104
TAG_RECTANGLE_SIMPLE_ROUNDED_REFORMED = 1105  # Deprecated
TAG_RECTANGLE_SIMPLE_ROUNDED_STELLATED = 1106  # Deprecated
TAG_RECTANGLE_SIMPLE_ROUNDED_STELLATED_REFORMED = 1107  # Deprecated
TAG_RECTANGLE_COMPLEX = 1108
TAG_RECTANGLE_COMPLEX_REFORMED = 1109  # Deprecated
TAG_RECTANGLE_COMPLEX_STELLATED = 1110  # Deprecated
TAG_RECTANGLE_COMPLEX_STELLATED_REFORMED = 1111  # Deprecated
TAG_RECTANGLE_COMPLEX_ROUNDED = 1112
TAG_RECTANGLE_COMPLEX_ROUNDED_REFORMED = 1113  # Deprecated
TAG_RECTANGLE_COMPLEX_ROUNDED_STELLATED = 1114  # Deprecated
TAG_RECTANGLE_COMPLEX_ROUNDED_STELLATED_REFORMED = 1115  # Deprecated

# Polygons
TAG_POLYGON_COMPLEX = 1200
TAG_POLYGON_COMPLEX_REFORMED = 1201  # Deprecated
TAG_POLYGON_COMPLEX_STELLATED = 1212  # Deprecated
TAG_POLYGON_COMPLEX_STELLATED_REFORMED = 1213  # Deprecated
TAG_POLYGON_COMPLEX_ROUNDED = 1214
TAG_POLYGON_COMPLEX_ROUNDED_REFORMED = 1215
TAG_POLYGON_COMPLEX_ROUNDED_STELLATED = 1216
TAG_POLYGON_COMPLEX_ROUNDED_STELLATED_REFORMED = 1217  # Deprecated

# General regular shapes
TAG_REGULAR_SHAPE_PHASE_1 = 1900
TAG_REGULAR_SHAPE_PHASE_2 = 1901

# Text related records
# Text definitions
TAG_FONT_DEF_TRUETYPE = 2000
TAG_FONT_DEF_ATM = 2001

# vanilla text story objects
TAG_TEXT_STORY_SIMPLE = 2100
TAG_TEXT_STORY_COMPLEX = 2101

# text story objects on a path
TAG_TEXT_STORY_SIMPLE_START_LEFT = 2110
TAG_TEXT_STORY_SIMPLE_START_RIGHT = 2111
TAG_TEXT_STORY_SIMPLE_END_LEFT = 2112
TAG_TEXT_STORY_SIMPLE_END_RIGHT = 2113
TAG_TEXT_STORY_COMPLEX_START_LEFT = 2114
TAG_TEXT_STORY_COMPLEX_START_RIGHT = 2115
TAG_TEXT_STORY_COMPLEX_END_LEFT = 2116  # Deprecated
TAG_TEXT_STORY_COMPLEX_END_RIGHT = 2117

# Text story information records
TAG_TEXT_STORY_WORD_WRAP_INFO = 2150
TAG_TEXT_STORY_INDENT_INFO = 2151

# other text story related objects
TAG_TEXT_LINE = 2200
TAG_TEXT_STRING = 2201
TAG_TEXT_CHAR = 2202
TAG_TEXT_EOL = 2203
TAG_TEXT_KERN = 2204
TAG_TEXT_CARET = 2205
TAG_TEXT_LINE_INFO = 2206

# Text attributes
TAG_TEXT_LINESPACE_RATIO = 2900
TAG_TEXT_LINESPACE_ABSOLUTE = 2901
TAG_TEXT_JUSTIFICATION_LEFT = 2902
TAG_TEXT_JUSTIFICATION_CENTRE = 2903
TAG_TEXT_JUSTIFICATION_RIGHT = 2904
TAG_TEXT_JUSTIFICATION_FULL = 2905
TAG_TEXT_FONT_SIZE = 2906
TAG_TEXT_FONT_TYPEFACE = 2907
TAG_TEXT_BOLD_ON = 2908
TAG_TEXT_BOLD_OFF = 2909
TAG_TEXT_ITALIC_ON = 2910
TAG_TEXT_ITALIC_OFF = 2911
TAG_TEXT_UNDERLINE_ON = 2912
TAG_TEXT_UNDERLINE_OFF = 2913
TAG_TEXT_SCRIPT_ON = 2914
TAG_TEXT_SCRIPT_OFF = 2915
TAG_TEXT_SUPERSCRIPT_ON = 2916
TAG_TEXT_SUBSCRIPT_ON = 2917
TAG_TEXT_TRACKING = 2918
TAG_TEXT_ASPECT_RATIO = 2919
TAG_TEXT_BASELINE = 2920

# Imagesetting attributes
TAG_OVERPRINTLINEON = 3500
TAG_OVERPRINTLINEOFF = 3501
TAG_OVERPRINTFILLON = 3502
TAG_OVERPRINTFILLOFF = 3503
TAG_PRINTONALLPLATESON = 3504
TAG_PRINTONALLPLATESOFF = 3505

# Document Print/Imagesetting options
TAG_PRINTERSETTINGS = 3506
TAG_IMAGESETTING = 3507
TAG_COLOURPLATE = 3508

# Registration mark records
TAG_PRINTMARKDEFAULT = 3509
RESERVED_3510 = 3510

# Stroking records
TAG_VARIABLEWIDTHFUNC = 4000  # This record is not currently used
TAG_VARIABLEWIDTHTABLE = 4001
TAG_STROKETYPE = 4002 
TAG_STROKEDEFINITION = 4003  # This record is not currently used
TAG_STROKEAIRBRUSH = 4004  # This record is not currently used

# Fractal Noise records
TAG_NOISEFILL = 4010
TAG_NOISETRANSPARENTFILL = 4011

# Mould bounds record
TAG_MOULD_BOUNDS = 4012

# Bitmap export hint record
TAG_EXPORT_HINT = 4015

# Web Address tags
TAG_WEBADDRESS = 4020
TAG_WEBADDRESS_BOUNDINGBOX = 4021

# Frame layer tags
TAG_LAYER_FRAMEPROPS = 4030
TAG_SPREAD_ANIMPROPS = 4031

# Wizard properties tags
TAG_WIZOP = 4040
TAG_WIZOP_STYLE = 4041
TAG_WIZOP_STYLEREF = 4042

# Shadow tags
TAG_SHADOWCONTROLLER = 4050
TAG_SHADOW = 4051

# Bevel tags
TAG_BEVEL = 4052 
TAG_BEVATTR_INDENT = 4053  # Deprecated
TAG_BEVATTR_LIGHTANGLE = 4054  # Deprecated
TAG_BEVATTR_CONTRAST = 4055  # Deprecated
TAG_BEVATTR_TYPE = 4056  # Deprecated
TAG_BEVELINK = 4057

# Blend on a curve tags
TAG_BLENDER_CURVEPROP = 4060
TAG_BLEND_PATH = 4061
TAG_BLENDER_CURVEANGLES = 4062

# Contouring tags
TAG_CONTOURCONTROLLER = 4066
TAG_CONTOUR = 4067

# Set tags
TAG_SETSENTINEL = 4070
TAG_SETPROPERTY = 4071

# More Blend on a curve tags
TAG_BLENDPROFILES = 4072
TAG_BLENDERADDITIONAL = 4073
TAG_NODEBLENDPATH_FILLED = 4074

# Multi stage fill tags
TAG_LINEARFILLMULTISTAGE = 4075
TAG_CIRCULARFILLMULTISTAGE = 4076
TAG_ELLIPTICALFILLMULTISTAGE = 4077
TAG_CONICALFILLMULTISTAGE = 4078

# Brush attribute tags
TAG_BRUSHATTR = 4079
TAG_BRUSHDEFINITION = 4080
TAG_BRUSHDATA = 4081
TAG_MOREBRUSHDATA = 4082
TAG_MOREBRUSHATTR = 4083

# ClipView tags
TAG_CLIPVIEWCONTROLLER = 4084
TAG_CLIPVIEW = 4085

# Feathering tags
TAG_FEATHER = 4086

# Bar properties tag
TAG_BARPROPERTY = 4087

# Other multi stage fill tags
TAG_SQUAREFILLMULTISTAGE = 4088

# More brush tags
TAG_EVENMOREBRUSHDATA = 4102
TAG_EVENMOREBRUSHATTR = 4103
TAG_TIMESTAMPBRUSHDATA = 4104
TAG_BRUSHPRESSUREINFO = 4105
TAG_BRUSHPRESSUREDATA = 4106
TAG_BRUSHATTRPRESSUREINFO = 4107
TAG_BRUSHCOLOURDATA = 4108
TAG_BRUSHPRESSURESAMPLEDATA = 4109
TAG_BRUSHTIMESAMPLEDATA = 4110
TAG_BRUSHATTRFILLFLAGS = 4111
TAG_BRUSHTRANSPINFO = 4112
TAG_BRUSHATTRTRANSPINFO = 4113

# Nudge size record
TAG_DOCUMENTNUDGE = 4114

# Bitmap properties record
TAG_BITMAP_PROPERTIES = 4115

# Bitmap smoothing record
TAG_DOCUMENTBITMAPSMOOTHING = 4116

# XPE bitmap processing record
TAG_XPE_BITMAP_PROPERTIES = 4117

# XPE Bitmap file format placeholder record
TAG_DEFINEBITMAP_XPE = 4118

# Current attributes records
TAG_CURRENTATTRIBUTES = 4119
TAG_CURRENTATTRIBUTEBOUNDS = 4120

# = 3-point linear fill records
TAG_LINEARFILL3POINT = 4121
TAG_LINEARFILLMULTISTAGE3POINT = 4122
TAG_LINEARTRANSPARENTFILL3POINT = 4123

# Duplication distance record
TAG_DUPLICATIONOFFSET = 4124

# Bitmap effect tags
TAG_LIVE_EFFECT = 4125
TAG_LOCKED_EFFECT = 4126
TAG_FEATHER_EFFECT = 4127

# Miscellaneous records
TAG_COMPOUNDRENDER = 4128
TAG_OBJECTBOUNDS = 4129
TAG_SPREAD_PHASE2 = 4131
TAG_CURRENTATTRIBUTES_PHASE2 = 4132
TAG_SPREAD_FLASHPROPS = 4134
TAG_PRINTERSETTINGS_PHASE2 = 4135
TAG_DOCUMENTINFORMATION = 4136
TAG_CLIPVIEW_PATH = 4137
TAG_DEFINEBITMAP_PNG_REAL = 4138
TAG_TEXT_STRING_POS = 4139
TAG_SPREAD_FLASHPROPS2 = 4140
TAG_TEXT_LINESPACE_LEADING = 4141

# New text records
TAG_TEXT_TAB = 4200
TAG_TEXT_LEFT_INDENT = 4201
TAG_TEXT_FIRST_INDENT = 4202
TAG_TEXT_RIGHT_INDENT = 4203
TAG_TEXT_RULER = 4204
TAG_TEXT_STORY_HEIGHT_INFO = 4205
TAG_TEXT_STORY_LINK_INFO = 4206
TAG_TEXT_STORY_TRANSLATION_INFO = 4207
TAG_TEXT_SPACE_BEFORE = 4208
TAG_TEXT_SPACE_AFTER = 4209
TAG_TEXT_SPECIAL_HYPHEN = 4210
TAG_TEXT_SOFT_RETURN = 4211
TAG_TEXT_EXTRA_FONT_INFO = 4212
TAG_TEXT_EXTRA_TT_FONT_DEF = 4213
TAG_TEXT_EXTRA_ATM_FONT_DEF = 4214


XAR_ID = {

    # Navigation records
    TAG_UP: "UP",
    TAG_DOWN: "DOWN",
    TAG_FILEHEADER: "FILEHEADER",
    TAG_ENDOFFILE: "ENDOFFILE",

    # Tag management
    TAG_ATOMICTAGS: "ATOMICTAGS",
    TAG_ESSENTIALTAGS: "ESSENTIALTAGS",
    TAG_TAGDESCRIPTION: "TAGDESCRIPTION",

    # Compression tags
    TAG_STARTCOMPRESSION: "STARTCOMPRESSION",
    TAG_ENDCOMPRESSION: "ENDCOMPRESSION",

    # Document tags
    TAG_DOCUMENT: "DOCUMENT",
    TAG_CHAPTER: "CHAPTER",
    TAG_SPREAD: "SPREAD",

    # Notes

    TAG_LAYER: "LAYER",
    TAG_PAGE: "PAGE",
    TAG_SPREADINFORMATION: "SPREADINFORMATION",
    TAG_GRIDRULERSETTINGS: "GRIDRULERSETTINGS",
    TAG_GRIDRULERORIGIN: "GRIDRULERORIGIN",
    TAG_LAYERDETAILS: "LAYERDETAILS",
    TAG_GUIDELAYERDETAILS: "GUIDELAYERDETAILS",
    TAG_SPREADSCALING_ACTIVE: "SPREADSCALING ACTIVE",
    TAG_SPREADSCALING_INACTIVE: "SPREADSCALING INACTIVE",

    # Colour reference tags
    TAG_DEFINERGBCOLOUR: "DEFINERGBCOLOUR",
    TAG_DEFINECOMPLEXCOLOUR: "DEFINECOMPLEXCOLOUR",

    # Bitmap reference tags

    TAG_PREVIEWBITMAP_GIF: "PREVIEWBITMAP GIF",
    TAG_PREVIEWBITMAP_JPEG: "PREVIEWBITMAP JPEG",
    TAG_PREVIEWBITMAP_PNG: "PREVIEWBITMAP PNG",



    TAG_DEFINEBITMAP_JPEG: "DEFINEBITMAP JPEG",
    TAG_DEFINEBITMAP_PNG: "DEFINEBITMAP PNG",


    TAG_DEFINEBITMAP_JPEG8BPP: "DEFINEBITMAP JPEG8BPP",

    # View tags
    TAG_VIEWPORT: "VIEWPORT",
    TAG_VIEWQUALITY: "VIEWQUALITY",
    TAG_DOCUMENTVIEW: "DOCUMENTVIEW",

    # Document unit tags
    TAG_DEFINE_PREFIXUSERUNIT: "DEFINE PREFIXUSERUNIT",
    TAG_DEFINE_SUFFIXUSERUNIT: "DEFINE SUFFIXUSERUNIT",
    TAG_DEFINE_DEFAULTUNITS: "DEFINE DEFAULTUNITS",

    # Document info tags
    TAG_DOCUMENTCOMMENT: "DOCUMENTCOMMENT",
    TAG_DOCUMENTDATES: "DOCUMENTDATES",
    TAG_DOCUMENTUNDOSIZE: "DOCUMENTUNDOSIZE",
    TAG_DOCUMENTFLAGS: "DOCUMENTFLAGS",
    TAG_DOCUMENTINFORMATION: "DOCUMENTINFORMATION",

    # Object tags
    TAG_PATH: "PATH",
    TAG_PATH_FILLED: "PATH FILLED",
    TAG_PATH_STROKED: "PATH STROKED",
    TAG_PATH_FILLED_STROKED: "PATH FILLED STROKED",
    TAG_GROUP: "GROUP",
    TAG_BLEND: "BLEND",
    TAG_BLENDER: "BLENDER",
    TAG_MOULD_ENVELOPE: "MOULD ENVELOPE",
    TAG_MOULD_PERSPECTIVE: "MOULD PERSPECTIVE",
    TAG_MOULD_GROUP: "MOULD GROUP",
    TAG_MOULD_PATH: "MOULD PATH",
    TAG_PATH_FLAGS: "PATH FLAGS",
    TAG_GUIDELINE: "GUIDELINE",
    TAG_PATH_RELATIVE: "PATH RELATIVE",
    TAG_PATH_RELATIVE_FILLED: "PATH RELATIVE FILLED",
    TAG_PATH_RELATIVE_STROKED: "PATH RELATIVE STROKED",
    TAG_PATH_RELATIVE_FILLED_STROKED: "PATH RELATIVE FILLED STROKED",

    TAG_PATHREF_TRANSFORM: "PATHREF TRANSFORM",

    # Attribute tags
    TAG_FLATFILL: "FLATFILL",
    TAG_LINECOLOUR: "LINECOLOUR",
    TAG_LINEWIDTH: "LINEWIDTH",
    TAG_LINEARFILL: "LINEARFILL",
    TAG_CIRCULARFILL: "CIRCULARFILL",
    TAG_ELLIPTICALFILL: "ELLIPTICALFILL",
    TAG_CONICALFILL: "CONICALFILL",
    TAG_BITMAPFILL: "BITMAPFILL",
    TAG_CONTONEBITMAPFILL: "CONTONEBITMAPFILL",
    TAG_FRACTALFILL: "FRACTALFILL",
    TAG_FILLEFFECT_FADE: "FILLEFFECT FADE",
    TAG_FILLEFFECT_RAINBOW: "FILLEFFECT RAINBOW",
    TAG_FILLEFFECT_ALTRAINBOW: "FILLEFFECT ALTRAINBOW",
    TAG_FILL_REPEATING: "FILL REPEATING",
    TAG_FILL_NONREPEATING: "FILL NONREPEATING",
    TAG_FILL_REPEATINGINVERTED: "FILL REPEATINGINVERTED",
    TAG_FLATTRANSPARENTFILL: "FLATTRANSPARENTFILL",
    TAG_LINEARTRANSPARENTFILL: "LINEARTRANSPARENTFILL",
    TAG_CIRCULARTRANSPARENTFILL: "CIRCULARTRANSPARENTFILL",
    TAG_ELLIPTICALTRANSPARENTFILL: "ELLIPTICALTRANSPARENTFILL",
    TAG_CONICALTRANSPARENTFILL: "CONICALTRANSPARENTFILL",
    TAG_BITMAPTRANSPARENTFILL: "BITMAPTRANSPARENTFILL",
    TAG_FRACTALTRANSPARENTFILL: "FRACTALTRANSPARENTFILL",
    TAG_LINETRANSPARENCY: "LINETRANSPARENCY",
    TAG_STARTCAP: "STARTCAP",
    TAG_ENDCAP: "ENDCAP",
    TAG_JOINSTYLE: "JOINSTYLE",
    TAG_MITRELIMIT: "MITRELIMIT",
    TAG_WINDINGRULE: "WINDINGRULE",
    TAG_QUALITY: "QUALITY",
    TAG_TRANSPARENTFILL_REPEATING: "TRANSPARENTFILL REPEATING",
    TAG_TRANSPARENTFILL_NONREPEATING: "TRANSPARENTFILL NONREPEATING",
    TAG_TRANSPARENTFILL_REPEATINGINVERTED: "TRANSPARENTFILL REPEATINGINVERTED",

    # Arrows and dash patterns
    TAG_DASHSTYLE: "DASHSTYLE",
    TAG_DEFINEDASH: "DEFINEDASH",
    TAG_ARROWHEAD: "ARROWHEAD",
    TAG_ARROWTAIL: "ARROWTAIL",
    TAG_DEFINEARROW: "DEFINEARROW",
    TAG_DEFINEDASH_SCALED: "DEFINEDASH SCALED",

    # User Attributes
    TAG_USERVALUE: "USERVALUE",

    # special colour fills
    TAG_FLATFILL_NONE: "FLATFILL NONE",
    TAG_FLATFILL_BLACK: "FLATFILL BLACK",
    TAG_FLATFILL_WHITE: "FLATFILL WHITE",
    TAG_LINECOLOUR_NONE: "LINECOLOUR NONE",
    TAG_LINECOLOUR_BLACK: "LINECOLOUR BLACK",
    TAG_LINECOLOUR_WHITE: "LINECOLOUR WHITE",

    # Bitmaps
    TAG_NODE_BITMAP: "NODE BITMAP",
    TAG_NODE_CONTONEDBITMAP: "NODE CONTONEDBITMAP",

    # New fill type records
    TAG_DIAMONDFILL: "DIAMONDFILL",
    TAG_DIAMONDTRANSPARENTFILL: "DIAMONDTRANSPARENTFILL",
    TAG_THREECOLFILL: "THREECOLFILL",
    TAG_THREECOLTRANSPARENTFILL: "THREECOLTRANSPARENTFILL",
    TAG_FOURCOLFILL: "FOURCOLFILL",
    TAG_FOURCOLTRANSPARENTFILL: "FOURCOLTRANSPARENTFILL",
    TAG_FILL_REPEATING_EXTRA: "FILL REPEATING EXTRA",
    TAG_TRANSPARENTFILL_REPEATING_EXTRA: "TRANSPARENTFILL REPEATING EXTRA",

    # Regular shapes
    # Ellipses
    TAG_ELLIPSE_SIMPLE: "ELLIPSE SIMPLE",
    TAG_ELLIPSE_COMPLEX: "ELLIPSE COMPLEX",

    # Rectangles
    TAG_RECTANGLE_SIMPLE: "RECTANGLE SIMPLE",
    TAG_RECTANGLE_SIMPLE_REFORMED: "RECTANGLE SIMPLE REFORMED",  # Deprecated
    TAG_RECTANGLE_SIMPLE_STELLATED: "RECTANGLE SIMPLE STELLATED",  # Deprecated
    TAG_RECTANGLE_SIMPLE_STELLATED_REFORMED: "RECTANGLE SIMPLE STELLATED REFORMED",  # Deprecated
    TAG_RECTANGLE_SIMPLE_ROUNDED: "RECTANGLE SIMPLE ROUNDED",
    TAG_RECTANGLE_SIMPLE_ROUNDED_REFORMED: "RECTANGLE SIMPLE ROUNDED REFORMED",  # Deprecated
    TAG_RECTANGLE_SIMPLE_ROUNDED_STELLATED: "RECTANGLE SIMPLE ROUNDED STELLATED",  # Deprecated
    TAG_RECTANGLE_SIMPLE_ROUNDED_STELLATED_REFORMED: "RECTANGLE SIMPLE ROUNDED STELLATED REFORMED",  # Deprecated
    TAG_RECTANGLE_COMPLEX: "RECTANGLE COMPLEX",
    TAG_RECTANGLE_COMPLEX_REFORMED: "RECTANGLE COMPLEX REFORMED",  # Deprecated
    TAG_RECTANGLE_COMPLEX_STELLATED: "RECTANGLE COMPLEX STELLATED",  # Deprecated
    TAG_RECTANGLE_COMPLEX_STELLATED_REFORMED: "RECTANGLE COMPLEX STELLATED REFORMED",  # Deprecated
    TAG_RECTANGLE_COMPLEX_ROUNDED: "RECTANGLE COMPLEX ROUNDED",
    TAG_RECTANGLE_COMPLEX_ROUNDED_REFORMED: "RECTANGLE COMPLEX ROUNDED REFORMED",  #  Deprecated
    TAG_RECTANGLE_COMPLEX_ROUNDED_STELLATED: "RECTANGLE COMPLEX ROUNDED STELLATED",  # Deprecated
    TAG_RECTANGLE_COMPLEX_ROUNDED_STELLATED_REFORMED: "RECTANGLE COMPLEX ROUNDED STELLATED REFORMED",  #  Deprecated

    # Polygons
    TAG_POLYGON_COMPLEX: "POLYGON COMPLEX",
    TAG_POLYGON_COMPLEX_REFORMED: "POLYGON COMPLEX REFORMED",  # Deprecated
    TAG_POLYGON_COMPLEX_STELLATED: "POLYGON COMPLEX STELLATED",  # Deprecated
    TAG_POLYGON_COMPLEX_STELLATED_REFORMED: "POLYGON COMPLEX STELLATED REFORMED",  # Deprecated
    TAG_POLYGON_COMPLEX_ROUNDED: "POLYGON COMPLEX ROUNDED",
    TAG_POLYGON_COMPLEX_ROUNDED_REFORMED: "POLYGON COMPLEX ROUNDED REFORMED",
    TAG_POLYGON_COMPLEX_ROUNDED_STELLATED: "POLYGON COMPLEX ROUNDED STELLATED",
    TAG_POLYGON_COMPLEX_ROUNDED_STELLATED_REFORMED: "POLYGON COMPLEX ROUNDED STELLATED REFORMED",  # Deprecated

    # General regular shapes
    TAG_REGULAR_SHAPE_PHASE_1: "REGULAR SHAPE PHASE 1",
    TAG_REGULAR_SHAPE_PHASE_2: "REGULAR SHAPE PHASE 2",

    # Text related records
    # Text definitions
    TAG_FONT_DEF_TRUETYPE: "FONT DEF TRUETYPE",
    TAG_FONT_DEF_ATM: "FONT DEF ATM",

    # vanilla text story objects
    TAG_TEXT_STORY_SIMPLE: "TEXT STORY SIMPLE",
    TAG_TEXT_STORY_COMPLEX: "TEXT STORY COMPLEX",

    # text story objects on a path
    TAG_TEXT_STORY_SIMPLE_START_LEFT: "TEXT STORY SIMPLE START LEFT",
    TAG_TEXT_STORY_SIMPLE_START_RIGHT: "TEXT STORY SIMPLE START RIGHT",
    TAG_TEXT_STORY_SIMPLE_END_LEFT: "TEXT STORY SIMPLE END LEFT",
    TAG_TEXT_STORY_SIMPLE_END_RIGHT: "TEXT STORY SIMPLE END RIGHT",
    TAG_TEXT_STORY_COMPLEX_START_LEFT: "TEXT STORY COMPLEX START LEFT",
    TAG_TEXT_STORY_COMPLEX_START_RIGHT: "TEXT STORY COMPLEX START RIGHT",
    TAG_TEXT_STORY_COMPLEX_END_LEFT: "TEXT STORY COMPLEX END LEFT",  # Deprecated
    TAG_TEXT_STORY_COMPLEX_END_RIGHT: "TEXT STORY COMPLEX END RIGHT",

    # Text story information records
    TAG_TEXT_STORY_WORD_WRAP_INFO: "TEXT STORY WORD WRAP INFO",
    TAG_TEXT_STORY_INDENT_INFO: "TEXT STORY INDENT INFO",

    # other text story related objects
    TAG_TEXT_LINE: "TEXT LINE",
    TAG_TEXT_STRING: "TEXT STRING",
    TAG_TEXT_CHAR: "TEXT CHAR",
    TAG_TEXT_EOL: "TEXT EOL",
    TAG_TEXT_KERN: "TEXT KERN",
    TAG_TEXT_CARET: "TEXT CARET",
    TAG_TEXT_LINE_INFO: "TEXT LINE INFO",

    # Text attributes
    TAG_TEXT_LINESPACE_RATIO: "TEXT LINESPACE RATIO",
    TAG_TEXT_LINESPACE_ABSOLUTE: "TEXT LINESPACE ABSOLUTE",
    TAG_TEXT_JUSTIFICATION_LEFT: "TEXT JUSTIFICATION LEFT",
    TAG_TEXT_JUSTIFICATION_CENTRE: "TEXT JUSTIFICATION CENTRE",
    TAG_TEXT_JUSTIFICATION_RIGHT: "TEXT JUSTIFICATION RIGHT",
    TAG_TEXT_JUSTIFICATION_FULL: "TEXT JUSTIFICATION FULL",
    TAG_TEXT_FONT_SIZE: "TEXT FONT SIZE",
    TAG_TEXT_FONT_TYPEFACE: "TEXT FONT TYPEFACE",
    TAG_TEXT_BOLD_ON: "TEXT BOLD ON",
    TAG_TEXT_BOLD_OFF: "TEXT BOLD OFF",
    TAG_TEXT_ITALIC_ON: "TEXT ITALIC ON",
    TAG_TEXT_ITALIC_OFF: "TEXT ITALIC OFF",
    TAG_TEXT_UNDERLINE_ON: "TEXT UNDERLINE ON",
    TAG_TEXT_UNDERLINE_OFF: "TEXT UNDERLINE OFF",
    TAG_TEXT_SCRIPT_ON: "TEXT SCRIPT ON",
    TAG_TEXT_SCRIPT_OFF: "TEXT SCRIPT OFF",
    TAG_TEXT_SUPERSCRIPT_ON: "TEXT SUPERSCRIPT ON",
    TAG_TEXT_SUBSCRIPT_ON: "TEXT SUBSCRIPT ON",
    TAG_TEXT_TRACKING: "TEXT TRACKING",
    TAG_TEXT_ASPECT_RATIO: "TEXT ASPECT RATIO",
    TAG_TEXT_BASELINE: "TEXT BASELINE",

    # Imagesetting attributes
    TAG_OVERPRINTLINEON: "OVERPRINTLINEON",
    TAG_OVERPRINTLINEOFF: "OVERPRINTLINEOFF",
    TAG_OVERPRINTFILLON: "OVERPRINTFILLON",
    TAG_OVERPRINTFILLOFF: "OVERPRINTFILLOFF",
    TAG_PRINTONALLPLATESON: "PRINTONALLPLATESON",
    TAG_PRINTONALLPLATESOFF: "PRINTONALLPLATESOFF",

    # Document Print/Imagesetting options
    TAG_PRINTERSETTINGS: "PRINTERSETTINGS",
    TAG_IMAGESETTING: "IMAGESETTING",
    TAG_COLOURPLATE: "COLOURPLATE",

    # Registration mark records
    TAG_PRINTMARKDEFAULT: "PRINTMARKDEFAULT",


    # Stroking records
    TAG_VARIABLEWIDTHFUNC: "VARIABLEWIDTHFUNC", 
    TAG_VARIABLEWIDTHTABLE: "VARIABLEWIDTHTABLE", 
    TAG_STROKETYPE: "STROKETYPE", 
    TAG_STROKEDEFINITION: "STROKEDEFINITION",
    TAG_STROKEAIRBRUSH: "STROKEAIRBRUSH",

    # Fractal Noise records
    TAG_NOISEFILL: "NOISEFILL",
    TAG_NOISETRANSPARENTFILL: "NOISETRANSPARENTFILL",

    # Mould bounds record
    TAG_MOULD_BOUNDS: "MOULD BOUNDS",

    # Bitmap export hint record
    TAG_EXPORT_HINT: "EXPORT HINT",

    # Web Address tags
    TAG_WEBADDRESS: "WEBADDRESS",
    TAG_WEBADDRESS_BOUNDINGBOX: "WEBADDRESS BOUNDINGBOX",

    # Frame layer tags
    TAG_LAYER_FRAMEPROPS: "LAYER FRAMEPROPS",
    TAG_SPREAD_ANIMPROPS: "SPREAD ANIMPROPS",

    # Wizard properties tags
    TAG_WIZOP: "WIZOP",
    TAG_WIZOP_STYLE: "WIZOP STYLE",
    TAG_WIZOP_STYLEREF: "WIZOP STYLEREF",

    # Shadow tags
    TAG_SHADOWCONTROLLER: "SHADOWCONTROLLER",
    TAG_SHADOW: "SHADOW",

    # Bevel tags
    TAG_BEVEL: "BEVEL", 
    TAG_BEVATTR_INDENT: "BEVATTR INDENT",  #  Deprecated
    TAG_BEVATTR_LIGHTANGLE: "BEVATTR LIGHTANGLE",  #  Deprecated
    TAG_BEVATTR_CONTRAST: "BEVATTR CONTRAST",  #  Deprecated
    TAG_BEVATTR_TYPE: "BEVATTR TYPE",  #  Deprecated
    TAG_BEVELINK: "BEVELINK",

    # Blend on a curve tags
    TAG_BLENDER_CURVEPROP: "BLENDER CURVEPROP",
    TAG_BLEND_PATH: "BLEND PATH",
    TAG_BLENDER_CURVEANGLES: "BLENDER CURVEANGLES",

    # Contouring tags
    TAG_CONTOURCONTROLLER: "CONTOURCONTROLLER",
    TAG_CONTOUR: "CONTOUR",

    # Set tags
    TAG_SETSENTINEL: "SETSENTINEL",
    TAG_SETPROPERTY: "SETPROPERTY",

    # More Blend on a curve tags
    TAG_BLENDPROFILES: "BLENDPROFILES",
    TAG_BLENDERADDITIONAL: "BLENDERADDITIONAL",
    TAG_NODEBLENDPATH_FILLED: "NODEBLENDPATH FILLED",

    # Multi stage fill tags
    TAG_LINEARFILLMULTISTAGE: "LINEARFILLMULTISTAGE",
    TAG_CIRCULARFILLMULTISTAGE: "CIRCULARFILLMULTISTAGE",
    TAG_ELLIPTICALFILLMULTISTAGE: "ELLIPTICALFILLMULTISTAGE",
    TAG_CONICALFILLMULTISTAGE: "CONICALFILLMULTISTAGE",

    # Brush attribute tags
    TAG_BRUSHATTR: "BRUSHATTR",
    TAG_BRUSHDEFINITION: "BRUSHDEFINITION",
    TAG_BRUSHDATA: "BRUSHDATA",
    TAG_MOREBRUSHDATA: "MOREBRUSHDATA",
    TAG_MOREBRUSHATTR: "MOREBRUSHATTR",

    # ClipView tags
    TAG_CLIPVIEWCONTROLLER: "CLIPVIEWCONTROLLER",
    TAG_CLIPVIEW: "CLIPVIEW",

    # Feathering tags
    TAG_FEATHER: "FEATHER",

    # Bar properties tag
    TAG_BARPROPERTY: "BARPROPERTY",

    # Other multi stage fill tags
    TAG_SQUAREFILLMULTISTAGE: "SQUAREFILLMULTISTAGE",

    # More brush tags
    TAG_EVENMOREBRUSHDATA: "EVENMOREBRUSHDATA",
    TAG_EVENMOREBRUSHATTR: "EVENMOREBRUSHATTR",
    TAG_TIMESTAMPBRUSHDATA: "TIMESTAMPBRUSHDATA",
    TAG_BRUSHPRESSUREINFO: "BRUSHPRESSUREINFO",
    TAG_BRUSHPRESSUREDATA: "BRUSHPRESSUREDATA",
    TAG_BRUSHATTRPRESSUREINFO: "BRUSHATTRPRESSUREINFO",
    TAG_BRUSHCOLOURDATA: "BRUSHCOLOURDATA",
    TAG_BRUSHPRESSURESAMPLEDATA: "BRUSHPRESSURESAMPLEDATA",
    TAG_BRUSHTIMESAMPLEDATA: "BRUSHTIMESAMPLEDATA",
    TAG_BRUSHATTRFILLFLAGS: "BRUSHATTRFILLFLAGS",
    TAG_BRUSHTRANSPINFO: "BRUSHTRANSPINFO",
    TAG_BRUSHATTRTRANSPINFO: "BRUSHATTRTRANSPINFO",

    # Nudge size record
    TAG_DOCUMENTNUDGE: "DOCUMENTNUDGE",

    # Bitmap properties record
    TAG_BITMAP_PROPERTIES: "BITMAP PROPERTIES",

    # Bitmap smoothing record
    TAG_DOCUMENTBITMAPSMOOTHING: "DOCUMENTBITMAPSMOOTHING",

    # XPE bitmap processing record
    TAG_XPE_BITMAP_PROPERTIES: "XPE BITMAP PROPERTIES",

    # XPE Bitmap file format placeholder record
    TAG_DEFINEBITMAP_XPE: "DEFINEBITMAP XPE",

    # Current attributes records
    TAG_CURRENTATTRIBUTES: "CURRENTATTRIBUTES",
    TAG_CURRENTATTRIBUTEBOUNDS: "CURRENTATTRIBUTEBOUNDS",

    # = 3-point linear fill records
    TAG_LINEARFILL3POINT: "LINEARFILL3POINT",
    TAG_LINEARFILLMULTISTAGE3POINT: "LINEARFILLMULTISTAGE3POINT",
    TAG_LINEARTRANSPARENTFILL3POINT: "LINEARTRANSPARENTFILL3POINT",

    # Duplication distance record
    TAG_DUPLICATIONOFFSET: "DUPLICATIONOFFSET",

    # Bitmap effect tags
    TAG_LIVE_EFFECT: "LIVE EFFECT",
    TAG_LOCKED_EFFECT: "LOCKED EFFECT",
    TAG_FEATHER_EFFECT: "FEATHER EFFECT",

    # Miscellaneous records
    TAG_COMPOUNDRENDER: "COMPOUNDRENDER",
    TAG_OBJECTBOUNDS: "OBJECTBOUNDS",
    TAG_SPREAD_PHASE2: "SPREAD PHASE2",
    TAG_CURRENTATTRIBUTES_PHASE2: "CURRENTATTRIBUTES PHASE2",
    TAG_SPREAD_FLASHPROPS: "SPREAD FLASHPROPS",
    TAG_PRINTERSETTINGS_PHASE2: "PRINTERSETTINGS PHASE2",
    TAG_DOCUMENTINFORMATION: "DOCUMENTINFORMATION",
    TAG_CLIPVIEW_PATH: "CLIPVIEW PATH",
    TAG_DEFINEBITMAP_PNG_REAL: "DEFINEBITMAP PNG REAL",
    TAG_TEXT_STRING_POS: "TEXT STRING POS",
    TAG_SPREAD_FLASHPROPS2: "SPREAD FLASHPROPS2",
    TAG_TEXT_LINESPACE_LEADING: "TEXT LINESPACE LEADING",

    # New text records
    TAG_TEXT_TAB: "TEXT TAB",
    TAG_TEXT_LEFT_INDENT: "TEXT LEFT INDENT",
    TAG_TEXT_FIRST_INDENT: "TEXT FIRST INDENT",
    TAG_TEXT_RIGHT_INDENT: "TEXT RIGHT INDENT",
    TAG_TEXT_RULER: "TEXT RULER",
    TAG_TEXT_STORY_HEIGHT_INFO: "TEXT STORY HEIGHT INFO",
    TAG_TEXT_STORY_LINK_INFO: "TEXT STORY LINK INFO",
    TAG_TEXT_STORY_TRANSLATION_INFO: "TEXT STORY TRANSLATION INFO",
    TAG_TEXT_SPACE_BEFORE: "TEXT SPACE BEFORE",
    TAG_TEXT_SPACE_AFTER: "TEXT SPACE AFTER",
    TAG_TEXT_SPECIAL_HYPHEN: "TEXT SPECIAL HYPHEN",
    TAG_TEXT_SOFT_RETURN: "TEXT SOFT RETURN",
    TAG_TEXT_EXTRA_FONT_INFO: "TEXT EXTRA FONT INFO",
    TAG_TEXT_EXTRA_TT_FONT_DEF: "TEXT EXTRA TT FONT DEF",
    TAG_TEXT_EXTRA_ATM_FONT_DEF: "TEXT EXTRA ATM FONT DEF",
}